DROP TABLE SOURCE_USER IF EXISTS ;

DROP TABLE SOURCE_GROUP IF EXISTS ;

CREATE TABLE SOURCE_USER  (
	ID VARCHAR(100) IDENTITY NOT NULL PRIMARY KEY,
	NAME VARCHAR(32) NOT NULL,
);


CREATE TABLE SOURCE_GROUP  (
	ID VARCHAR(100) IDENTITY NOT NULL PRIMARY KEY,
	NAME VARCHAR(32) NOT NULL,
);

insert into SOURCE_USER VALUES('11', 'USER1');
insert into SOURCE_USER VALUES('2', 'USER2');
insert into SOURCE_USER VALUES('3', 'USER3');
insert into SOURCE_USER VALUES('4', 'USER4');
insert into SOURCE_USER VALUES('5', 'USER5');

insert into SOURCE_GROUP VALUES('11', 'GROUP1');
insert into SOURCE_GROUP VALUES('2', 'GROUP2');
insert into SOURCE_GROUP VALUES('3', 'GROUP3');
insert into SOURCE_GROUP VALUES('4', 'GROUP4');
insert into SOURCE_GROUP VALUES('5', 'GROUP5');
insert into SOURCE_GROUP VALUES('6', 'GROUP6');

COMMIT;
